_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 1cb5c6a8-228e-4809-88b2-53a0ed4f6378
name: 'OUE Assessment | Georgia Institute of Technology | Atlanta, GA'
mail: cory.hopkins@gatech.edu
slogan: 'Continuous improvement through assessment.'
page:
  403: /node/3
  404: /node/4
  front: /node/126
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
